const sampleData = [
    {
      name: "John Doe",
      phonenumber: 1234567890,
      location: "123 Main Street",
      bloodgroup: "O+",
      date_of_joining: new Date("2020-01-01"),
      active: true,
      age: 30,
      skills: ["Node.js", "React", "MongoDB"],
      position:"Software Developer",
      officelocation:"San Fransico",
      salary:34000,
    },
    {
      name: "Jane Smith",
      phonenumber: 0987654321,
      location: "456 Maple Street",
      bloodgroup: "AB-",
      date_of_joining: new Date("2019-01-01"),
      active: true,
      age: 28,
      skills: ["Express.js", "Angular", "Mongodb"],
      position:"Software Developer",
      officelocation:"San Fransico",
      salary:14000,
    },
    {
        name: "Saranya",
        phonenumber: 0987654421,
        location: "456 Manhattan Street",
        bloodgroup: "B-",
        date_of_joining: new Date("2019-01-01"),
        active: true,
        age: 30,
        skills: ["Express.js", "Angular", "PostgreSQL"],
        position:"Software Developer",
        officelocation:"San Fransico",
        salary:14000,
      },
      {
        name: "Harsha",
        phonenumber: 0917654321,
        location: "456 Little Manhattan Street",
        bloodgroup: "A-",
        date_of_joining: new Date("2019-01-01"),
        active: false,
        age: 23,
        skills: ["Express.js", "Angular", "React"],
        position:"Software Developer",
        officelocation:"San Fransico",
        salary:25000,
      },
      {
        name: "Tony Skyes",
        phonenumber: 0987650321,
        location: "4516 Maple Street",
        bloodgroup: "O-",
        date_of_joining: new Date("2019-01-01"),
        active: true,
        age: 28,
        skills: ["Express.js", "Angular", "Docker"],
        position:"Software Developer",
        officelocation:"San Fransico",
        salary:35000,
      },
    // Add more objects as needed
  ];


  module.exports = sampleData;